# Generated by Django 3.2.23 on 2024-08-30 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarybook',
            options={'ordering': ['author'], 'verbose_name_plural': 'Library'},
        ),
    ]
