# Generated by Django 3.2.23 on 2024-08-30 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_librarybook_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='librarybook',
            old_name='availabole',
            new_name='available',
        ),
    ]
